load("//:rules.bzl", "rntop_cc_auto_library")

rntop_cc_auto_library(
    name = "app",
    deps = [
        "//arguments",
        "//cluster",
        "//gui/window",
        "//ncurses/color",
        "//ncurses/session",
    ],
)
