load("//:rules.bzl", "rntop_cc_auto_library")

rntop_cc_auto_library(
    name = "factory",
    deps = [
        "//agent/agent",
        "//agent/libssh",
        "//agent/local",
        "//agent/ssh",
        "//agent/type",
    ],
)
