load("//:rules.bzl", "rntop_cc_auto_library")

rntop_cc_auto_library(
    name = "node",
    deps = [
        "//agent/agent",
        "//device",
        "//metric",
        "//ssh",
        "//utils",
    ],
)
